# SOURCE: https://swimburger.net/blog/dotnet/how-to-deploy-aspnet-blazor-webassembly-to-github-pages
name: Deploy to Github Pages
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
permissions: write-all

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 3.1
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7.0.x
      - name: Publish .NET Core Project
        run: dotnet publish Blazor-WebAssembly-Portfolio/Blazor-WebAssembly-Portfolio.csproj -c Release -o release --nologo
      
            # changes the base-tag in index.html from '/' to 'BlazorGitHubPagesDemo' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html from / to BlazorGitHubPagesDemo
        run: sed -i 's/<base href="\/" \/>/<base href="\/Blazor-WebAssembly-Portfolio\/" \/>/g' release/wwwroot/index.html
        
#     # copy index.html to 404.html to serve the same file when a file is not found
#     - name: copy index.html to 404.html
#       run: cp release/wwwroot/index.html release/wwwroot/404.html
        # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      
      - name: Commit wwwroot to Github Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot

